workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get Flutter packages
        script: flutter pub get

      - name: Copy .env.example to .env
        script: cp .env.example .env

      - name: Install CocoaPods dependencies (fast)
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo remove master || true
          pod setup --sources=https://cdn.cocoapods.org/
          pod install
          cd ..

      - name: Build iOS release IPA
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
